scrape_configs:
  - job_name: "uptime-monitor-service"
    metrics_path: /api/metrics
    static_configs:
      - targets: [ "uptime-monitor:3000" ]
    relabel_configs:
      - target_label: app_name
        replacement: uptime-monitor

global:
  scrape_interval: 3s
