Postgres:
  port: 6132
  host: localhost
  user: postgres
  password: postgres
  DBName: uptime_monitor_db
  sslMode: disable

Server:
  host: "0.0.0.0"
  port: "3000"

Monitor:
  intervalSeconds: 60
  requestTimeoutSeconds: 5
  historyLimit: 100
  maxConcurrency: 5
